GET http://localhost:5155/PaymentMethod

###
GET http://localhost:5155/PaymentMethod/7


###
POST http://localhost:5155/PaymentMethod
Content-Type: application/json

{
  "methodName": "new Credit Card"
}


###
PUT http://localhost:5155/PaymentMethod/7
Content-Type: application/json

{
  "methodName": "Credit Card updated"
}


###
DELETE  http://localhost:5155/PaymentMethod/7